io:
  image_dir: img
  mask_dir: img_sam
  image_size: [480,640]
  logit_size: [256,256]  # DO NOT change UNLESS you know what you're doing

gui:
  icon: icon.png
  window_size: [1400, 1200]
  canvas_size: [480,640]
  list_size: [15,8]
  label_font:
    - times new roman
    - 16
  button_font:
    - times new roman
    - 14
  palette:
    canvas: "#949698"
    Point-P: "#3C8031"
    Point-N: "#AA1803"
    Box: "#92268F"
    BoxHaning: "#BBFFFF"
    Highlight: "#FFFFFF"
    mask: [30, 144, 255, 150]  # "RGBA"

  marker_size:
    point: 7
    point_width: 3
    box: 5

sam:
  checkpoint: checkpoint/sam_vit_b_01ec64.pth
  model: vit_b  # [vit_h, vit_l, vit_b]
  device: cpu
  model_size:
    vit_b: 0.34928543772548437
    vit_l: 1.163710474036634
    vit_h: 2.3884241273626685

